version: '3.8'
services:
  moneysavior:
#    build: .
    image: nda2105/moneysavior:latest
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    restart: on-failure
  mysqldb:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=moneysavior
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql_data: