server:
  port: 8080

spring:
  datasource:
    url: #Import from Railway variables
    username: #Import from Railway variables
    password: #Import from Railway variables
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # Hoặc create, create-drop, validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true