server:
  port: 8080

spring:
  application:
    name: moneysavior
  profiles:
    active: local, secrets

springdoc:
  swagger-ui:
    path: /

openai:
  api:
    url: https://api.openai.com
    model: gpt-4.1-nano-2025-04-14